### ISSUE TITLE
Donwload Drop-down list should show download links

### ISSUE THREAD

**Issue by mcinnisb** [Allsteel/hni-textiles-webcomponents#101]
Felipe if you could create the drop-down list for the Download button that contains the "Download" links that are on the current site and use the same layout you and Mateus had in the original mobile site that would be great. @mbr4nt can help with the look of this based on the original mobile enabled site. @mbr4nt can you paste in a screenshot of that original downloads drop down menu?

**Comment by felipebbtoledo** [comment]
@mbr4nt I will work on that.

**Comment by felipebbtoledo** [comment]
@mbr4nt Please make its content dynamic and visible/hidden accordingly.
