### ISSUE TITLE
Product Availability Accordian Menu

### ISSUE THREAD

**Issue by mcinnisb** [Allsteel/hni-textiles-webcomponents#103]
If it's too complex to create the accordian menu, then we should follow the same facets we have today where there each split out. If that's the case then we can assign this ticket to Brandon Garret once he's in GitHub.

**Comment by mbr4nt** [comment]
@mcinnisb there's no way to split those into multiple facets because of the hierarchy between them, unfortunately. I'll just go ahead and make the accordion.
