### ISSUE TITLE
Textiles Search Page - Images are not all the same size

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#104]
Some images of the fabric tiles are not all the same size.

Please see attachment.
![fabricsquareuneven3](https://cloud.githubusercontent.com/assets/13138473/10541850/ca2c256e-73d9-11e5-9e75-db7d9f2b6e16.JPG)

![fabricsquareuneven4](https://cloud.githubusercontent.com/assets/13138473/10583467/c4045c3a-7652-11e5-94e3-ff20ecf4ae60.JPG)

![fabricsquareuneven](https://cloud.githubusercontent.com/assets/13138473/10583485/de7d236c-7652-11e5-9a49-711933516e45.JPG)

**Comment by mbr4nt** [comment]
@WilliamsHeidi those are the best we had in AO. Can you please reach out to Kandice and ask for a higher res image? In general, the resolution of the swatches is really bad. It doesn't show so here in the search page but in the detail page it looks pretty awful. We need better swatches for everything.

**Comment by WilliamsHeidi** [comment]
@mbr4nt for the Pattern Abito, I show that this is from HBF Textiles.  It was my understanding that we had all their high resolution images on a CD.  Can those be uploaded to correct the resolution issue here?

**Comment by mbr4nt** [comment]
it can. Do you have anyone that can do the work?

**Comment by mbr4nt** [comment]
Rudy will fix this by uploading the HBF high res swatches to scene7

**Comment by RudyValenz** [comment]
I've gone through and scrolled through the fabrics page to verify that all images have been corrected and spacing between image and copy looks correct. @WilliamsHeidi @hamiltonk  would you like to verify?
