### ISSUE TITLE
Textiles Search Page - Missing Images

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#105]
There are some images not coming up.  Are these missing?  Do we need to track images down for these? Or do these just have an error?
![missing images](https://cloud.githubusercontent.com/assets/13138473/10541913/0e418ffa-73da-11e5-87e1-3e2e1ca89f7b.JPG)

![missing images2](https://cloud.githubusercontent.com/assets/13138473/10583523/1469bfb2-7653-11e5-9fbd-ec98ed51c132.JPG)

![missing images3](https://cloud.githubusercontent.com/assets/13138473/10583537/18d4b368-7653-11e5-8218-3e097abdcb0d.JPG)

![missing images4](https://cloud.githubusercontent.com/assets/13138473/10583540/1eae44ca-7653-11e5-91c6-0728d7662595.JPG)

![missing images5](https://cloud.githubusercontent.com/assets/13138473/10583553/2f7f857a-7653-11e5-9813-a350dfa1019b.JPG)

**Comment by mcinnisb** [comment]
@mbr4nt can you take a quick look and find out why images are showing up broken this morning. Wondering if it's Tuca's server.

**Comment by mbr4nt** [comment]
@tucaz , this is because this image is too large to serve. Instead of asking for the full image (scl=1) we need to put a cap on the image size to be server. can you please change the api to return the image urls like this: http://s7d4.scene7.com/is/image/hnicorp/maharam-mimic-clay?wid=800&fit=constrain,0

**Comment by tucaz** [comment]
Data updated

![image](https://cloud.githubusercontent.com/assets/111954/10552808/065da4e4-741c-11e5-9fea-1bad9908af68.png)

**Comment by WilliamsHeidi** [comment]
there are more missing images.

**Comment by WilliamsHeidi** [comment]
Do you need screenshots of all missing images?  There are a lot of them.  Please advice how you would like to move forward.

**Comment by mbr4nt** [comment]
Just name a few. Thanks.

On Monday, October 19, 2015, Heidi Williams <notifications@github.com>
wrote:

> Do you need screenshots of all missing images? There are a lot of them.
> Please advice how you would like to move forward.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Allsteel/hni-textiles-webcomponents/issues/105#issuecomment-149278850>
> .
>


-- 
Mateus Brant

**Comment by WilliamsHeidi** [comment]
I have put additional screenshots in the description above.

**Comment by mbr4nt** [comment]
done now. the few that will be still missing after this are some that we really don't have the image for.
