### ISSUE TITLE
Textiles Search Page - Pattern Name not on the left

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#106]
The Pattern Name below is not showing to the left of the page.
![patternname_not on the left](https://cloud.githubusercontent.com/assets/13138473/10542615/0d477556-73df-11e5-8ef3-3df71bc000d6.JPG)

**Comment by mbr4nt** [comment]
The missing image is breaking the layout. @WilliamsHeidi, can you please obtain the swatch from Kandice? We don't have this one in AO currently, see below:

![image](https://cloud.githubusercontent.com/assets/12057269/10545267/6e19a5e4-73ed-11e5-93e9-7a06c1f783c1.png)

**Comment by garrettbt** [comment]
@WilliamsHeidi - this fabric has been discontinued. I was waiting on something from Marketing to make changes to AO. Once I get the new spreadsheets loaded to PDW I will kick-off a new syndication to fix this.

**Comment by mbr4nt** [comment]
@garrettbt this evil textile is still in the syndication file.
