### ISSUE TITLE
Textiles Search Page - Color Family Ordering

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#109]
The color family needs to be in the same order as HBF Textiles.

Here is the order HBF Textiles has:
![hbfcolororder](https://cloud.githubusercontent.com/assets/13138473/10552165/820520ea-7417-11e5-859e-22d7661b0ec6.JPG)

**Comment by mbr4nt** [comment]
Facet sort options are by document count or by facet name.

**Comment by mcinnisb** [comment]
@mbr4nt What's the level of effort to have the color facets in the order above? They need to be in the same order as HBF Textiles.

**Comment by mbr4nt** [comment]
@mcinnisb the search engine does not offer the option to pick the sequence, probably given the dynamic nature of search results. We'd have to implement something custom. I'd rather not deal with this last minute. Can we discuss this post launch?

**Comment by mcinnisb** [comment]
Yeah, that works. I’m surprised something as simple as setting the order isn’t part of ES.

Brandon McInnis
Director, e-Business

Allsteel
Mobile 563.299.2885
mcinnisb@allsteeloffice.com<http://www.allsteeloffice.com/>
allsteeloffice.com<http://www.allsteeloffice.com/>
