### ISSUE TITLE
Search Terms

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#110]
I would like to know if there are specific search terms I should and should not be able to use at the moment. For example, I would expect to be able to use "floral", but perhaps those tags do not exist at this time. Logging as a question to get guidance on how to approach this.

**Comment by mbr4nt** [comment]
@hamiltonk A good place to start would be the facets. For instance, here are the pattern types. you can see floral isn't one of them:

![image](https://cloud.githubusercontent.com/assets/12057269/10590155/d80a5d48-7674-11e5-93ba-8b5d1b9f1750.png)
