### ISSUE TITLE
Textiles Search Page - Light Colored Tiles

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#113]
Is there a light shadow or something we can put on the tiles so that the really light or white ones show up? On the web site "Ermine" you cannot see.  In this image it is more visible.
![lightcoloredimages](https://cloud.githubusercontent.com/assets/13138473/10583367/1c8928c8-7652-11e5-9870-a67a16c603e6.JPG)

![lightcoloredimages2](https://cloud.githubusercontent.com/assets/13138473/10584150/2e9c6198-7656-11e5-8175-f5ddb887ddfe.JPG)

**Comment by mcinnisb** [comment]
@felipebbtoledo Felipe, can you add a grey border (pick a grey that you think works) to the images.

**Comment by felipebbtoledo** [comment]
I added a gray border to the tiles colored according to the legal palette colors.

**Comment by WilliamsHeidi** [comment]
In retesting this.  There are still some light colored tiles that you can't see.
![lightcoloredimages3](https://cloud.githubusercontent.com/assets/13138473/10613912/fe70ea1c-771c-11e5-90c5-693f4d32c45e.JPG)

**Comment by felipebbtoledo** [comment]
@WilliamsHeidi I'm not able to reproduce the issue, all tiles have a gray border around it, I tested in qa. Can you specify the steps to reproduce it? Check if it is a browser cache/cookie issue.
