### ISSUE TITLE
Textiles Detail Page - ACT Symbols

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#117]
ACT symbols need removed from the site.  ASI has not purchased the license to publish these and the purchase of this license was pushed in to 2016.

**Comment by mbr4nt** [comment]
@felipebbtoledo please remove the icons

**Comment by WilliamsHeidi** [comment]
ACT icons are still showing on the details page

**Comment by felipebbtoledo** [comment]
I talked to Heide, and she has confirmed it has been solved.
