### ISSUE TITLE
Textiles Detail Page - Pattern-Color Name

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#119]
The Pattern - Color name should be the first thing to appear in the attribute list as a heading.
![pattern_colorway_detailspage](https://cloud.githubusercontent.com/assets/13138473/10614470/1da2c452-7720-11e5-82fa-c3ff4e8975fb.JPG)

Currently, only the Colorway name is showing.
![colorway_detailspage](https://cloud.githubusercontent.com/assets/13138473/10614486/332d1854-7720-11e5-822c-32692f251ab0.JPG)

**Comment by mbr4nt** [comment]
waiting on @mcinnisb to confirm we want to go this route.

**Comment by mcinnisb** [comment]
Katie is correct. Should show Patter Color name with a dash between them.

**Comment by mbr4nt** [comment]
@tucaz please update the value coming as name in the api

**Comment by tucaz** [comment]
Fixed in QA
