### ISSUE TITLE
Textiles Detail Page - Repeat Attribute

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#122]
The repeat attribute needs to display as Vertical by Horizontal.

**Comment by mbr4nt** [comment]
data

**Comment by garrettbt** [comment]
This is being transformed on syndication. I will check with Luciano to see if he can change the transformation.

**Comment by garrettbt** [comment]
Luciano was able to change the transformation. Once this change has been moved to production I will re-syndicate.
