### ISSUE TITLE
Textiles Detail Page - Weight attribute

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#123]
The weight attribute needs to display with the wording "ounces per linear yard"

**Comment by mbr4nt** [comment]
needs to be fixed in the data

**Comment by garrettbt** [comment]
This would need to be transformed on syndication. I don't know if it would be easier for @mbr4nt place this phrasing on the page.

**Comment by garrettbt** [comment]
I take this back, this field is a text field and I can change that.

**Comment by garrettbt** [comment]
Complete in the PDW. Will go out in the next syndication.
