### ISSUE TITLE
Fabric Details Page - Configurator Missing

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#125]
There is no product configurator on the fabric details page. This is on Appoint. Some other patterns seem to have configurators, such as Perennial.

![2015_10_20_13_25_47_fabrics](https://cloud.githubusercontent.com/assets/14330996/10617094/38abccb8-772e-11e5-9749-c24e7f06ea65.png)

**Comment by mbr4nt** [comment]
There's no configurator for panel fabrics. We only have Seating configurators.
