### ISSUE TITLE
Fabric Details Page - Back to Search (Chrome)

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#126]
When viewing the Fabric Details Page in Chrome, I cannot use the Back To Search link. It will take me all the way back to the landing page. In IE11 this is not occurring, though.

![bts](https://cloud.githubusercontent.com/assets/14330996/10617725/931cb60a-7731-11e5-8060-cb493a73991a.png)

**Comment by mbr4nt** [comment]
works for me

**Comment by hamiltonk** [comment]
This is working today. Will continue to monitor.

**Comment by hamiltonk** [comment]
Kristi S. verified that this passes.
