### ISSUE TITLE
Fabric Details Page - Configurator Product Change

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#127]
I can select different products from the configurator list, but the product in the configurator does not change. This is true across multiple browsers.

![image](https://cloud.githubusercontent.com/assets/14330996/10640329/c69429c0-77d9-11e5-95df-00730c8cf9d4.png)

**Comment by tucaz** [comment]
@hamiltonk are you testing in QA? (http://qa.allsteeloffice.com/design-resources/textiles-and-finishes/fabrics/)

I tested in Chrome 46, Firefox 41 and Internet Explorer 11 and its working in all of them. 

Did you try to clear your browser cache or maybe hit CTRL + F5 to force a refresh?
