### ISSUE TITLE
add sku number to configurator

### ISSUE THREAD

**Issue by mbr4nt** [Allsteel/hni-textiles-webcomponents#129]
display sku number next to the picture

**Comment by tucaz** [comment]
@mbr4nt I added it below the text "Visualization". It is a simple binding for a property that is already there. @felipebbtoledo can put it anywhere you guys think it will fit better.

```
<span>{{sku}}</span>
```

![image](https://cloud.githubusercontent.com/assets/111954/10646890/4cdb92e0-77fb-11e5-8a29-b7253bd3088b.png)
