### ISSUE TITLE
Fabric Details Page - Available Colors

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#130]
Expected results: The correct colors are available when compared to the fabric pattern/color offering list.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern that has at least 8 colorways; click the colorway
5. Compare the available colors against this spreadsheet: http://hni.hnicorp.com/sites/ITProjectManagement/15-0062/Documents/GoLiveData/Copy of Copy of PDWExportByColorWay- KKT.xlsx 
6. Repeat steps 4-6 for a total of ten patterns that have at least eight colorways

**Comment by kensrudl** [comment]
Tested in Chrome and passed
