### ISSUE TITLE
Textile Search Page- Appoint

### ISSUE THREAD

**Issue by tjebkesk** [Allsteel/hni-textiles-webcomponents#132]
Please add the word  Panel after Appoint.  
![appoint panel](https://cloud.githubusercontent.com/assets/15112720/10646142/2cfd904e-77f7-11e5-8ed5-2b4d927b7195.png)

**Comment by garrettbt** [comment]
This has been changed in PDW. We will test it on the next syndication.

**Comment by SorensenK** [comment]
"Panel" didn't appear. Appoint stayed as-is and there was Appoint Seating.

**Comment by GordonPeg** [comment]
Reviewed and passed
