### ISSUE TITLE
Textile Search Page remove panel or seating after grade

### ISSUE THREAD

**Issue by tjebkesk** [Allsteel/hni-textiles-webcomponents#134]
Please remove the word Panel or Seating after Grade
![grade label](https://cloud.githubusercontent.com/assets/15112720/10646410/8c0bdc2a-77f8-11e5-88b5-d07a5df1a0b9.png)

**Comment by mbr4nt** [comment]
Data clean-up.

**Comment by garrettbt** [comment]
Complete in the PDW. Will go out with the next syndication.

**Comment by WilliamsHeidi** [comment]
this is still showing on the right-hand side of the page.  reopening per Kandice Tjebkes.

**Comment by GordonPeg** [comment]
Reviewed and passed
