### ISSUE TITLE
Filter List - Wrap

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#138]
Would it be possible to have the list of filters wrap so that names do not run behind the "X" to remove them? Alternatively we could adjust font size instead. We would just like to see the whole name.

This screenshot is from Chrome.

![wrap](https://cloud.githubusercontent.com/assets/14330996/10647837/66d97b26-7800-11e5-88a2-12773f1b1fb3.png)

**Comment by hawkinscad** [comment]
Same issue w/ color family white cream taupe

![image](https://cloud.githubusercontent.com/assets/15113901/10768913/5c4ae5c2-7cb1-11e5-8203-2e5dd67216e8.png)

**Comment by hawkinscad** [comment]
Still seems to be an issue
![image](https://cloud.githubusercontent.com/assets/15113901/10828848/ca535164-7e44-11e5-8706-e838455ed088.png)

**Comment by mcinnisb** [comment]
Agreed, still not correct.

**Comment by felipebbtoledo** [comment]
@mcinnisb Can you specify what browser are you getting that issue? I can't reproduce it in Chrome.

**Comment by mcinnisb** [comment]
Am using Chrome. Here’s a screenshot.

[cid:image002.jpg@01D11314.366AD620]

Brandon McInnis
Director, e-Business

Allsteel
Mobile 563.299.2885
mcinnisb@allsteeloffice.com<http://www.allsteeloffice.com/>
allsteeloffice.com<http://www.allsteeloffice.com/>

**Comment by felipebbtoledo** [comment]
Well, I tried a bunch of window sizes in Chrome and I can see that, but I will increase the right side margin to achieve more spacing avoiding elements to overlap.

**Comment by mbr4nt** [comment]
fixed
