### ISSUE TITLE
Textiles Search Page - Supplier Ordering

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#139]
Suppliers are in the wrong order.
Currently they show in this order.
![suppliers](https://cloud.githubusercontent.com/assets/13138473/10647937/22914330-7801-11e5-945c-373d89dedc3f.JPG)
The need to be in this order:
Allsteel
HBF
Edelman
Maharam
Momentum
Ultrafabrics

**Comment by mbr4nt** [comment]
Can't do. It's alpha.

**Comment by hamiltonk** [comment]
Logged #224 for supplier removal. The sorting is a pass.
