### ISSUE TITLE
Colony Heat Image Missing

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#140]
The fabric pattern Colony and colorway Heat is missing an image.

**Comment by RudyValenz** [comment]
I've uploaded correct images to Scene7. Images may have incorrect data. I would like @garrettbt to look into it.

**Comment by RudyValenz** [comment]
I've checked the images and they look correct.  @hamiltonk can you verify?

**Comment by WilliamsHeidi** [comment]
Closing since Kevin tagged it Passed
