### ISSUE TITLE
Browser Back Button Issue

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#141]
Kristi Scholfield tested this in Chrome. When she went form the fabrics search page and drilled down into a specific fabric details page, then used the browser's back button, she ran into an issue. Clicking the back button the first time scrolled the page down. Sometimes a second click will also scroll the page down more. The third time (and sometimes the second time) will take users back to the landing page.

**Comment by mbr4nt** [comment]
@tucaz can you change AO to use replaceState instead of pushState? http://spoiledmilk.com/blog/html5-changing-the-browser-url-without-refreshing-page/

**Comment by tucaz** [comment]
Fixed in QA

**Comment by hamiltonk** [comment]
Kristi verified that this is a pass.
