### ISSUE TITLE
Scroll Up Issue - Fabrics Search Page

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#142]
Kristi Scholfield tested this in Chrome. She selected the Cream/White/Taupe color family, but nothing loaded. She actually had to take the scroll bar and scroll all the way up to the top for the filter to apply. It appears that one had to be all the way at the top of the page, or nothing will begin loading. Angie Brauns was able to replicate this issue in Chrome as well.

**Comment by mbr4nt** [comment]
@tucaz please make the page auto-scroll to 0 on facet selection.

**Comment by hamiltonk** [comment]
Tested and this is working. Assigning to myself until this can be tested by the business.

**Comment by GordonPeg** [comment]
#142 
Reviewed and passed
