### ISSUE TITLE
Textiles Search Page - Pattern Type Ordering

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#143]
Pattern Types need to be in the following order:
Solid
Solid/Texture
Geometric
Organic
Stripe
Plaid

**Comment by mbr4nt** [comment]
@WilliamsHeidi we don't have ability to cherry pick filters, I can only sort them by name or by count. There are currently 3 bugs about the same thing. I'd recommend we discuss this ability as a post launch enhancement.
