### ISSUE TITLE
Back to Search - Location Issue (Chrome)

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#144]
When using the "back to search" link from the details page in Chrome, users are taken back to the top of the search page. In IE 11, they are returned to the area that they were browsing before entering the details page. Chrome should behave in the same way that IE is behaving.

**Comment by mbr4nt** [comment]
Agree, but would classify as low priority.

**Comment by mcinnisb** [comment]
Agreed, low priority. I'll still assign it to Mateus. We'll want to look into fixing this shortly after launch.

**Comment by mbr4nt** [comment]
Created a label for post launch stuff. will assign and close.
