### ISSUE TITLE
Missing Image - Chock Family

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#147]
Sami Miller was using Chrome to test. She had the offerings filtered to black. The Chock family's black colorway is missing.

![image](https://cloud.githubusercontent.com/assets/14330996/10648667/584d49d4-7805-11e5-8bb2-c0a562beed7d.png)

**Comment by mbr4nt** [comment]
@mcinnisb who will we assign missing images to? It's not a PDW issue nor a code one. It's really we don't have that swatch.

**Comment by mcinnisb** [comment]
@mbr4nt All missing images will be assigned to Rudy @RudyValenz  to track down.

**Comment by RudyValenz** [comment]
Chock is showing up correctly under the black filter. @hamiltonk 

![image](https://cloud.githubusercontent.com/assets/12956803/10850927/2d471eac-7ef6-11e5-8510-acb504c1e70c.png)

**Comment by WilliamsHeidi** [comment]
images are now available.
