### ISSUE TITLE
Textiles Detail Page - Pattern Name

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#155]
Pattern Name should not exist IN the list of attributes (after Grade).  Only at the top as the heading.
![patternname](https://cloud.githubusercontent.com/assets/13138473/10673458/8cde1f0a-78bb-11e5-97fc-527c4eced3e5.JPG)

**Comment by tucaz** [comment]
Fixed in QA
