### ISSUE TITLE
Pricing Grade

### ISSUE THREAD

**Issue by tjebkesk** [Allsteel/hni-textiles-webcomponents#162]
1.  Change Pricing Grade to just Grade
2.  Put Grade in the order of -
Seating 1
Seating 2
Seating 3
to
Seating 22
Leather L1
Leather L2
Panel A
Panel B
to 
Panel J

![grades](https://cloud.githubusercontent.com/assets/15112720/10695197/22af331e-7968-11e5-849a-ab9250f7ff6e.png)

**Comment by mbr4nt** [comment]
@tucaz please change the facet name to just grade then assign this to me. Thanks!

**Comment by tucaz** [comment]
Done @mbr4nt

**Comment by mbr4nt** [comment]
@tucaz it's not working. probably because they changed the pricing grade values to not contain the words anymore, so "Seating 1" is now simply "1". So I guess you need to update the sort list.

**Comment by tucaz** [comment]
Fixed in QA
