### ISSUE TITLE
Supplier

### ISSUE THREAD

**Issue by tjebkesk** [Allsteel/hni-textiles-webcomponents#163]
Supplier order needs to be
Allsteel
HBF Textiles
Edelman
Maharam
Momentum
Ultrafabrics

Please remove Pendelton and Spradling.

![supplier](https://cloud.githubusercontent.com/assets/15112720/10695457/634c0dc4-7969-11e5-9c9a-ae3a018275e2.png)

**Comment by tucaz** [comment]
Values are sorted.

@garrettbt please remove Pendelton and Spradling from data

**Comment by mbr4nt** [comment]
This is done from the sorting perspective. Just need to remove those suppliers they don't want, which is a  data task.
