### ISSUE TITLE
Landing Page Footer

### ISSUE THREAD

**Issue by scholfieldk** [Allsteel/hni-textiles-webcomponents#164]
#43 

Kristi Scholfeld, Chrome

Footer alignment does not match the production site. Also, the Allsteel footer logo and About Us buttons do not redirect you to the right location. 

![footer-alignment](https://cloud.githubusercontent.com/assets/15216592/10695720/d5047c7a-796a-11e5-88c1-a4ae323a6082.JPG)
![footer-links](https://cloud.githubusercontent.com/assets/15216592/10695724/d749878c-796a-11e5-868b-1619d73a0d13.JPG)

**Comment by mbr4nt** [comment]
Duplicate #171 

the footer is the same, no matter the page.
