### ISSUE TITLE
pattern type

### ISSUE THREAD

**Issue by tjebkesk** [Allsteel/hni-textiles-webcomponents#166]
![pattern type](https://cloud.githubusercontent.com/assets/15112720/10695560/e0b0f734-7969-11e5-8498-270af95b0fdb.png)

Patterns are to be in this order and mesh is not a pattern type

1.	 Solid 
2.	Solid/Texture
3.	Geometric- 
4.	Organic- 
5.	Stripe- 
6.	Plaid-

**Comment by mbr4nt** [comment]
@mcinnisb , there are a few about being able to cherry pick the facet values. I'd like to tackle that post launch, so we have enough time to design something sustainable. If we try to squeeze this in now I'll have to rig it.

**Comment by tucaz** [comment]
Fixed

**Comment by mcinnisb** [comment]
Going to keep this bug open, but assigned to McInnis, until we get direction on what to do with Mesh.

**Comment by hamiltonk** [comment]
Re-opening per comment posted yesterday.

**Comment by WilliamsHeidi** [comment]
Mesh is not a Pattern Type, per Kandice.
