### ISSUE TITLE
Incorrect Image for Sublime

### ISSUE THREAD

**Issue by SorensenK** [Allsteel/hni-textiles-webcomponents#168]
the Gold color under pattern Sublime has the wrong colorway displayed

![image](https://cloud.githubusercontent.com/assets/15238848/10695886/b430b210-796b-11e5-8514-d563f5c61c47.png)

**Comment by RudyValenz** [comment]
New images were uploaded on 10-26. @SorensenK , can you please verify the colorway again. Thanks!

**Comment by RudyValenz** [comment]
I've checked the colors on QA vs the color on the site.  The colorway looks correct to me.

**Comment by SorensenK** [comment]
It seems correct, as all the colorways are slightly off color. May need to readdress in the future.
