### ISSUE TITLE
Details Page Footer - links

### ISSUE THREAD

**Issue by scholfieldk** [Allsteel/hni-textiles-webcomponents#169]
#65 

Kristi Scholfield, Chrome

Footer alignment does not match the production site. Also, the Allsteel footer logo buttons do not redirect you to the landing page.

![footer-alignment](https://cloud.githubusercontent.com/assets/15216592/10695720/d5047c7a-796a-11e5-88c1-a4ae323a6082.JPG)
![allsteellogo](https://cloud.githubusercontent.com/assets/15216592/10695900/c94af55c-796b-11e5-8817-8c55e9a208e6.JPG)

**Comment by mbr4nt** [comment]
Duplicate #171
