### ISSUE TITLE
Search page - Footer

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#171]
#62 

Kristi Scholfield tested on Chrome and there are these issues:

The alignment of the columns does not match.
The Allsteel logo and About us links do not function; there is just an error.

![image](https://cloud.githubusercontent.com/assets/14330996/10696306/9f0eee0a-796c-11e5-83d6-d00f050cdbb2.png)
![image](https://cloud.githubusercontent.com/assets/14330996/10696313/a661df5a-796c-11e5-919f-a2a4bdd9a153.png)

**Comment by mbr4nt** [comment]
The alignment needed to change to make it mobile friendly. I'll fix the links.
