### ISSUE TITLE
Download Links Issue

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#172]
#47 

Kristi Scholfield tested this in Chrome and the following files do not download. There is a "page cannot be displayed" error.

Allsteel Care Guide - doesn't work
Beyond Textured Paint Card - doesn't work
HBF Textiles Product Matrix - doesn’t work
HBF Textiles Sell Sheet - doesn’t work
System and Seating Fabric Matrix - doesn't work

Additionally, when clicking outside the popup, the list does not disappear.

**Comment by mbr4nt** [comment]
that's because those documents don't exist in QA. they exist in prod.
