### ISSUE TITLE
Fabric Search Bugs

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#173]
#45 

Sami Miller tested in Chrome. Here is her feedback:

Green Search pulls Green but some other colors as well, such as pattern I-Beam, color Molten (listed as Red on AO.com). I tried to replicate but this time it didn’t pull up anything but green. It is missing some color blocks:

image
![image](https://cloud.githubusercontent.com/assets/14330996/10696384/1277a706-796d-11e5-8dc4-8af57769bbbb.png)

Searched Red and missing a color. Also, it pulled some colors that are listed on AO in other color families, such as Article, Butterscotch which is listed as beige.

image
![image](https://cloud.githubusercontent.com/assets/14330996/10696379/0e766a8e-796d-11e5-80b6-a76676b085e2.png)

image
![image](https://cloud.githubusercontent.com/assets/14330996/10696376/0a942af0-796d-11e5-9810-89287e0df05c.png)

Searching Yellow also pulls beige colors and even a Blue Green.

image
![image](https://cloud.githubusercontent.com/assets/14330996/10696373/052b59bc-796d-11e5-8ef6-56de19264f02.png)

image
![image](https://cloud.githubusercontent.com/assets/14330996/10696369/00ba6896-796d-11e5-8a18-bf778c55fc25.png)

I tried searching Pattern, Floral, and Floral/Leaf but no results (I confirmed on AO that we do have fabrics listed as floral/leaf pattern).

Geometric and Blue were good.

**Comment by mbr4nt** [comment]
Typing green in the search and selecting green in the color family facet will produce slightly different results. The facet is an exact filter. The keywords, though, will search for that work anywhere in the fabric data. For instance, "Molten" has "green" as a value for the "Finish" field. I looked at a few and all seem to match the criteria. Examples:

Molten has:  Finish = "Crypton® Green", 
Sandstone:  colorFamily = "Beige, Gold, Yellow",
Gulf: colorFamily = "Beige, Gold, Yellow",

As for patterns, don't compare them to AO. The data in production today is not the latest. A lot of modification were made for this project. If you want an accurate list of pattern that is up to date, look at the facet list in the new page: 

![image](https://cloud.githubusercontent.com/assets/12057269/10697142/0a0fca3c-7970-11e5-9c6b-76d41691948c.png)

As for the missing image for Colony, that is indeed an issue. Not a code issue, though. We just don't have that image. Someone (I'm guessing Kandice) needs to supply them. If you want to open an issue about that, please do. 

I'm closing this one.

Also, for future reference, please try to keep issues separate. It will be easier to address and communicate about them if they individually than multiple things in a single item, like this one.
