### ISSUE TITLE
HBF images

### ISSUE THREAD

**Issue by tjebkesk** [Allsteel/hni-textiles-webcomponents#174]
![hbf](https://cloud.githubusercontent.com/assets/15112720/10696309/a10464b0-796c-11e5-84d0-9acbc3f3a3c2.png)
Fabric image is fuzzy and very pilaxted.  Seems like all HBF are this same fuzzy

**Comment by mbr4nt** [comment]
Duplicate #104 

Rudy is working on uploading the hi res HBF textiles.
