### ISSUE TITLE
#85 Issues

### ISSUE THREAD

**Issue by hawkinscad** [Allsteel/hni-textiles-webcomponents#176]
Finishes do come up  and are clickable, however:
-resolution seems poor on several of these
-many finishes are showing up multiple times (see Burnished Cherry, they all say 'Veneer')
-many finishes say 'null' after you click on them next to the finish name

**Comment by hawkinscad** [comment]
#85

**Comment by mbr4nt** [comment]
All fixed, except the quality of the images.

**Comment by RudyValenz** [comment]
Images have been updated and null issue has been resolved.  Assigning the request to have @garrettbt determine the resolution for Burnished Cherry.
