### ISSUE TITLE
72 - Detail page missing Fabric Grade

### ISSUE THREAD

**Issue by GordonPeg** [Allsteel/hni-textiles-webcomponents#178]
#72

Chrome 

The detail page appears to be missing a Fabric or Price Grade attribute.

-Selected Appoint Seating - Lawn (Seating Grade 2)
-did not find Fabric or Pricing Grade as an attribute
-Repeated with several fabrics including Appoint Seating-Mandarin and Rift-Persimmon (Grade 4)
-checked production side for current price grades

[Textile testing_Test 72.pdf](https://github.com/Allsteel/hni-textiles-webcomponents/files/19512/Textile.testing_Test.72.pdf)

**Comment by mbr4nt** [comment]
@WilliamsHeidi I told you pricing grade was an important thing to show :)

**Comment by WilliamsHeidi** [comment]
@mbr4nt Here is what I have for attributes and their ordering:
![image](https://cloud.githubusercontent.com/assets/13138473/10700955/da3fdcd6-7986-11e5-8a60-0fc98eea6341.png)

with the exception of not showing ACT symbols at go-live.

If I told you not to display Grade, I'm sorry!

**Comment by mbr4nt** [comment]
@WilliamsHeidi we're still friends. :)

**Comment by tucaz** [comment]
Fixed in QA
