### ISSUE TITLE
Landing Page Header 

### ISSUE THREAD

**Issue by scholfieldk** [Allsteel/hni-textiles-webcomponents#180]
#33 

Kristi Scholfield, Chrome

QA header needs to match header in alignment, search bar style, and resource center/contact us placement.

![headeralignment](https://cloud.githubusercontent.com/assets/15216592/10697118/e3902726-796f-11e5-8fed-bb31a8fe23ac.JPG)

**Comment by mbr4nt** [comment]
Duplicate #175
