### ISSUE TITLE
Incorrect Image for Dolce

### ISSUE THREAD

**Issue by SorensenK** [Allsteel/hni-textiles-webcomponents#181]
Latte shows incorrect colorway

![image](https://cloud.githubusercontent.com/assets/15238848/10697255/95ee434e-7970-11e5-9a91-417d8fc76e4d.png)

![image](https://cloud.githubusercontent.com/assets/15238848/10697240/87d3897c-7970-11e5-9e8f-39ef275eae74.png)

**Comment by mbr4nt** [comment]
@mcinnisb , there are a few items about incorrect images or missing images or bad quality images. I don't know who you plan to have fix those, so I'll be assigning them to you for now.

**Comment by mbr4nt** [comment]
Made a label for this

**Comment by mcinnisb** [comment]
Assigning to Rudy to track down and correct.

**Comment by RudyValenz** [comment]
I have verified that the Latte colorway is correct. It is the same in QA as the Spradling site.

![image](https://cloud.githubusercontent.com/assets/12956803/10854467/e786f856-7f09-11e5-85c2-0cb0e1a05dff.png)
