### ISSUE TITLE
Question around supplier field

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#182]
Is it possible on the DETAILS page to show the supplier only when an offering is tagged as a "partnership" program type? Example:

Fabric A - Partnership
Fabric B - Standard
Fabric C - COM
Fabric D - Standard
Fabric E - Standard
Fabric F - Partnership

Fabrics A and F WOULD should supplier in the details view; Fabrics B-E would NOT show the supplier label or value.

ASI business will decide how to proceed based on the answer to this question from @tjebkesk.

**Comment by mbr4nt** [comment]
Not with the amount of time we have. Could be a post launch enhancement.

**Comment by hamiltonk** [comment]
Communicated response to the business.
