### ISSUE TITLE
79 - Detail page missing Configurators

### ISSUE THREAD

**Issue by GordonPeg** [Allsteel/hni-textiles-webcomponents#183]
#79 
Chrome 

Some detail pages appears to be missing the configurator.  The hero images and smaller swatch image look good but when I was checking the configurator, it was missing on several patterns

-Selected Appoint Seating - Lawn (Seating Grade 2)
-Hero image look correct (not sure of the resolution)
-Checked for the configurator and it was not on the page
-Repeated several times and received mixed results - 
      Perennial is correct, 
      Chatterbox is missing configurator

[Textile testing_Test 79.pdf](https://github.com/Allsteel/hni-textiles-webcomponents/files/19528/Textile.testing_Test.79.pdf)

**Comment by mbr4nt** [comment]
To make a configurator show, the fabric needs to:
1 - be available on the product
2 - be in scene7 as a repeatable tile. Not all fabrics are there at this point nor will be available for launch.

For the ones that meet both criteria, the configurator shows up like it should.

I'm closing this issue.

**Comment by hamiltonk** [comment]
Changing to a question. @mbr4nt - Could you please give a list of the patterns that are ready at this time for configurators? We don't know which patterns to test yet. If you or your team could just document the list here, and then assign this back to me, I will make sure the right patterns are tested.

**Comment by tucaz** [comment]
Heidi has the list of missing fabrics. All fabrics except those should be good. I'm closing this.
