### ISSUE TITLE
available on 

### ISSUE THREAD

**Issue by tjebkesk** [Allsteel/hni-textiles-webcomponents#185]
![supplier](https://cloud.githubusercontent.com/assets/15112720/10697558/23a38ef0-7972-11e5-8ed3-ea6de1daa2d5.png)

#84 

The display of what products are available is off.

**Comment by tjebkesk** [comment]
![available](https://cloud.githubusercontent.com/assets/15112720/10698762/57381e10-7978-11e5-939c-dfab3f2c6145.png)

Please attached.  the Sum Work stool display is off.  Thanks

**Comment by mbr4nt** [comment]
Fixed. Might be a day to show up because Scene7 caches images. Please wait to test until tomorrow, 10/27.
