### ISSUE TITLE
Zoomed in images

### ISSUE THREAD

**Issue by tjebkesk** [Allsteel/hni-textiles-webcomponents#186]
![inertia](https://cloud.githubusercontent.com/assets/15112720/10697647/a27cfacc-7972-11e5-9ccc-7706660d7ecb.png)
The images are way too zoomed in across the board, makes the fabrics looks really bad

**Comment by mcinnisb** [comment]
I'll keep this assigned to me until all images have been verified.

**Comment by RudyValenz** [comment]
I've looked at the images.  I believe the zoomed in issue has been resolved (see screenshot). @tjebkesk please verify.

![image](https://cloud.githubusercontent.com/assets/12956803/10854610/c184de60-7f0a-11e5-964f-aeeeed3bb968.png)

**Comment by tjebkesk** [comment]
Can you please recheck Inertia as it still seems off?  Thanks

**Comment by RudyValenz** [comment]
Hi Kandice - @tjebkesk 

I've verified that we have high resolution images for Inertia. They are 1800 x 1800.

![image](https://cloud.githubusercontent.com/assets/12956803/10885143/6c4e9cea-8141-11e5-974e-bd449a31bb7b.png)

![image](https://cloud.githubusercontent.com/assets/12956803/10885173/8b070bb8-8141-11e5-97bf-85317d620b90.png)

**Comment by tjebkesk** [comment]
The individual images look great when you click on them.  My concern is the landing page images are very fuzzy and not clear looking.  Thanks

**Comment by RudyValenz** [comment]
@mbr4nt is this something you can look into for the Inertia fabric?

**Comment by mcinnisb** [comment]
This could just be how the pattern looks when it’s shrunk. Review it, in person, with Kandice and show her how it shrinks. Let me know if that doesn’t make sense.

Brandon McInnis
Director, e-Business

Allsteel
Mobile 563.299.2885
mcinnisb@allsteeloffice.com<http://www.allsteeloffice.com/>
allsteeloffice.com<http://www.allsteeloffice.com/>

**Comment by mbr4nt** [comment]
Exactly. When it shrinks down to the small swatch, the details are not
visible anymore.

**Comment by RudyValenz** [comment]
@mcinnisb I spoke with @tjebkesk. She suggested that the thumbnail should have more detail. I have modified the images for Inertia per the request.  Please see screen shots below.

![image](https://cloud.githubusercontent.com/assets/12956803/10999733/4fd833c6-8463-11e5-8a0a-612e18cd9099.png)

![image](https://cloud.githubusercontent.com/assets/12956803/10999858/fc8e2346-8463-11e5-87f0-81961ffe29f6.png)

**Comment by tjebkesk** [comment]
Rudy,

The thumb nails look awesome!!  The close up image is now off scale.

Brandon, this is the one we discussed yesterday about using two different images.  Can we pursue that?

Thanks, Kandice

**Comment by RudyValenz** [comment]
What are your thoughts on this @mcinnisb and @mbr4nt ?  Should I modify the image so that the resolution is between the original image size (1800 x 1800) and the current image size (900 x 900)?  The new image would be 1350 x 1350.  If you do not want me to modify the image please let me know.

Thanks,

Rudy

**Comment by tjebkesk** [comment]
Hi!  Any news on this?  Thanks

From: Tjebkes, Kandice (Allsteel)
Sent: Friday, November 06, 2015 11:48 AM
To: Allsteel/hni-textiles-webcomponents; Allsteel/hni-textiles-webcomponents; McInnis, Brandon (Allsteel)
Subject: RE: [hni-textiles-webcomponents] Zoomed in images (#186)- Inertia!!

Rudy,

The thumb nails look awesome!!  The close up image is now off scale.

Brandon, this is the one we discussed yesterday about using two different images.  Can we pursue that?

Thanks, Kandice
