### ISSUE TITLE
Detail View- Available On functionality

### ISSUE THREAD

**Issue by scholfieldk** [Allsteel/hni-textiles-webcomponents#188]
Kristi Scholfield, Chrome

We will need to verify all textiles, but when I select Appoint, and inspect the detail on each one, some do not have have "available on" product associated with them, and if they do (Appoint seating Turquoise) then show it's available on systems, but not seating. 

![missinginformationondetailspage](https://cloud.githubusercontent.com/assets/15216592/10697818/6e5e94de-7973-11e5-87bd-f0021ffde3a2.JPG)
![missinginformationondetailspage2](https://cloud.githubusercontent.com/assets/15216592/10697819/6e600a94-7973-11e5-96f4-03d66b498385.JPG)

**Comment by mbr4nt** [comment]
@garrettbt I checked and all the colors are consistent within the same fabric. What seems to be the issue here is that Appoint Seating seems to not be associated with any product. Can you please check?

**Comment by GordonPeg** [comment]
Reviewed product availability for Appoint Seating and Panels.  Passed
