### ISSUE TITLE
fabric code

### ISSUE THREAD

**Issue by tjebkesk** [Allsteel/hni-textiles-webcomponents#189]
![silvertex](https://cloud.githubusercontent.com/assets/15112720/10698070/acf8e496-7974-11e5-9d5a-bb5746220d91.png)

Fabric code is incorrect

**Comment by garrettbt** [comment]
@tjebkesk  - I will happily change this if you can provide me with the corrected information.

**Comment by tjebkesk** [comment]
Sorry that would help.  The code is SX.  Thanks

**Comment by GordonPeg** [comment]
Reviewed and approved
