### ISSUE TITLE
Fabric Attributes Issues

### ISSUE THREAD

**Issue by kensrudl** [Allsteel/hni-textiles-webcomponents#190]
#78 

Tested appoint seating in Chrome- 
Repeat Missing
backing missing
sustainability is extra and should not be on the list
Product restrictions/exceptions/notes is missing
Grade missing

**Comment by WilliamsHeidi** [comment]
@mbr4nt is it a true statement to say that if the attribute doesn't exist that it doesn't show.  For example, Backing?

**Comment by mbr4nt** [comment]
yes

**Comment by WilliamsHeidi** [comment]
@hamiltonk  we will need to determine how to validate the list of attributes.

**Comment by hamiltonk** [comment]
@GordonPeg  - If you are still able to test for the business this afternoon, please check the order of attributes. The test steps are in #78.
