### ISSUE TITLE
Image Download Format Issuw

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#196]
#68 

Not able to select format for image download.

![image](https://cloud.githubusercontent.com/assets/14330996/10700898/7818a74a-7986-11e5-9d0b-825da3cf64e5.png)

**Comment by mbr4nt** [comment]
@mcinnisb I completely  missed that. I remember now I did promise it. Can it be post launch, though?

**Comment by mbr4nt** [comment]
Merging #194 #195 #196, need to address all but will keep just one conversation going.

**Comment by mcinnisb** [comment]
@mbr4nt Mateus, can we just offer JPG? Not sure why we need all the different options. For launch let's just have "Large" and "JPG".

**Comment by mbr4nt** [comment]
@mcinnisb, yes. In fact, that's what you get when you click the download button: the largest jpg we have. Can I label this as post launch and close it?

**Comment by mcinnisb** [comment]
Will tackle this post launch. As part of the post launch conversation want to make sure we need all the options. I think we just need large and JPG, but want to confirm.
