### ISSUE TITLE
Dress Macdoland Colorway

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#200]
The colorway for Dress Macdonald on the textiles search and details pages does not match the other colorways. Please verify if this was on the DVD - maybe it was missing. If it was not on the DVD, Mateus asked for this to be assigned to him.

![image](https://cloud.githubusercontent.com/assets/14330996/10703223/20a945e2-7994-11e5-82f5-7c391492bc2a.png)

#67

**Comment by RudyValenz** [comment]
@hamiltonk , @mbr4nt  -The Dress McDonald had two versions in Scene7.  The old version (275x275) is named Dress Macdonald. The new version is named Dress McDonald http://s7d4.scene7.com/is/image/HBF/Hipster90444DressMcDonald?$DownloadImage$

Before I remove the old version, who needs to know about the correct name?

**Comment by hamiltonk** [comment]
Please change Hipster > Dress MacDonald to Hipster Dress McDonald.
