### ISSUE TITLE
Data Issue - Moguls

### ISSUE THREAD

**Issue by SorensenK** [Allsteel/hni-textiles-webcomponents#204]
#77 

Moguls

Content: 100% Terratex Recycled Polyester
Repeat: .8" V x .26" H

**Comment by GordonPeg** [comment]
#204

Repeat is not correct.  Listed above as   .26    but is displaying    26

**Comment by hamiltonk** [comment]
Assigning to Brandon G. as a data issue per Tammy S.

**Comment by GordonPeg** [comment]
Reviewed and passed
