### ISSUE TITLE
Element Pattern Details Page

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#207]
When clicking one of the colorways under the Element pattern, the details page displays without the other colors showing under the hero image. All of the colors seem to work okay when going from Search > Details. Also, in the same browser I can click on other patterns and see the colorways under the respective patterns.

![element](https://cloud.githubusercontent.com/assets/14330996/10732093/67140b1e-7bc6-11e5-8ab5-50796c0fb484.png)

**Comment by mcinnisb** [comment]
Verified and all is working as intended.
