### ISSUE TITLE
breadcrumb layout

### ISSUE THREAD

**Issue by mbr4nt** [Allsteel/hni-textiles-webcomponents#209]
recent changes broke the layout

![image](https://cloud.githubusercontent.com/assets/12057269/10732439/15af5d30-7bc8-11e5-9ae4-d38a37ee7027.png)

**Comment by felipebbtoledo** [comment]
@mbr4nt this has been fixed, now it needs to be updated in qa.

**Comment by tucaz** [comment]
@felipebbtoledo I just updated QA with the latest, but it doesn't seem to be fixed. Can you please verify that your fix is in there?
