### ISSUE TITLE
Inspirational Tiles Not Working

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#214]
When clicking the colorways on the inspirational tiles, they go nowhere. It just makes a whole bunch of breadcrumbs keep adding on (cumulative).

![inspirational](https://cloud.githubusercontent.com/assets/14330996/10742000/cba15366-7bf8-11e5-9c7e-01982146f9a5.png)

**Comment by mbr4nt** [comment]
@tucaz please take a look at the breadcrumb part. Don't worry about the tile not working, I'll check on that.

**Comment by hamiltonk** [comment]
Verified that both are now resolved.
