### ISSUE TITLE
Discontinued HBF Offerings

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#216]
The following pattern/color combinations have been discontinued by HBF and should no longer be a part of the offerings listed on the site. This information is from Tammy Price at HBF. Please remove these from the offerings on AO/AO QA.

Pattern	Color
Andante Encore	Olivio
Coco	Cassis
Coco	Caviar
Coco	Mimizan
Eyelet	Blue Tie
Eyelet	Caramel
Eyelet	Deep Red
Eyelet	Espresso
Eyelet	Mousse
Eyelet	On The Green
Eyelet	Silver Shadow
Eyelet	Snow Cream
Forest Light	Birch
Forest Light	Dusk
Forest Light	Fern
Forest Light	Flint
Forest Light	Fox
Forest Light	Glow
Forest Light	Nectar
Forest Light	Rain
Forest Light	Shade
Forest Light	Thistle
Forest Light	Trail
Gesture	Gris
Richmond	Frieze
Richmond	Neon
Savile Row Stripe	Boxwood
Savile Row Stripe	London Fog
Savile Row Stripe	Oxblood
Savile Row Stripe	Thames
Shoreline Stripe	Copper
Shoreline Stripe	Gravel
Shoreline Stripe	Moss
Shoreline Stripe	Sand
Straight Plush	Boggy
Straight Plush	Lichen
Vis-à-Vis	Acorn
Vis-à-Vis	Coconut
Vis-à-Vis	Juniper
Vis-à-Vis	Linen
Vis-à-Vis	Moss
Wavelength	Fig
Wavelength	Glow
Wavelength	Mushroom
Wavelength	Ocean
Wavelength	Orchid
Wavelength	Pistachio
Wavelength	Sandstone
Wavelength	Stainless
Woodland Trace	Fern
Woodland Trace	Nextar
Woodland Trace	Rain
Woodland Trace	Sandstone
Woodland Trace	Thistle

**Comment by hamiltonk** [comment]
Adding @tjebkesk @SorensenK @WilliamsHeidi  for visibility.

**Comment by GordonPeg** [comment]
#216

Reviewed and passed
