### ISSUE TITLE
HBF Clay Wall offerings

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#217]
@tjebkesk @SorensenK - On HBFTextiles.com the pattern is called Clay Wall, but on AO it is listed as Claywall. Is this a data error, or is ASI marketing the offering as one word intentionally?

**Comment by SorensenK** [comment]
We should be using HBF's name "Clay Wall" and that is how we show it in the MDS as well. I'll still ask that @tjebkesk verify.

**Comment by tjebkesk** [comment]
Agreed should be Clay Wall. Thanks

On Oct 27, 2015, at 9:10 AM, Kayla Sorensen <notifications@github.com<mailto:notifications@github.com>> wrote:


We should be using HBF's name "Clay Wall" and that is how we show it in the MDS as well. I'll still ask that @tjebkesk<https://github.com/tjebkesk> verify.
