### ISSUE TITLE
Colony Details

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#218]
When clicking on any of the colorways for the pattern Colony from the search page, I am given a blank details page. I have tried a cache clear and browser re-start. The odd thing is that it's just this pattern right now. All other patterns load data.

![colony](https://cloud.githubusercontent.com/assets/14330996/10760220/705d842a-7c89-11e5-8997-bc751a410e29.png)

**Comment by mbr4nt** [comment]
@tucaz, the server is returning a 500. http://qa-esapi.azurewebsites.net/allsteel/details/SHBFCLY11

**Comment by mbr4nt** [comment]
Play has issues too.

**Comment by tucaz** [comment]
Fixed in QA

**Comment by hamiltonk** [comment]
Confirmed as resolved.
