### ISSUE TITLE
Disappearing Back-to-Search link in IE 11

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#219]
In IE11, sometimes the Back-to-Search link disappears. It happens when clicking different colorways within the same pattern. I haven't noticed a certain number of clicks or anything, though.

![back_to_search](https://cloud.githubusercontent.com/assets/14330996/10761321/d46a9d86-7c8e-11e5-9771-47126604ef49.png)

**Comment by tucaz** [comment]
@hamiltonk it happens when you share the link with someone (or refresh the page being in the details) since we don't save the search state across requests. This is by design.

**Comment by mbr4nt** [comment]
It was happening on IE. Also the clicks on the color icons weren't working all the time. I sure fixed the clicks, and it appears that fixed the back link issue too.

**Comment by hamiltonk** [comment]
Appears to be resolved now.

**Comment by GordonPeg** [comment]
Retested and passed
