### ISSUE TITLE
Grade filter results count of "1" not returning swatch results

### ISSUE THREAD

**Issue by GordonPeg** [Allsteel/hni-textiles-webcomponents#220]
#160
Chrome

-Grade filter shows count but when selected it does not return any results:
    -Selected Seating
    -Expanded Grade and selected Grade “E (1)”
     -No results and retested using “H (1).
    -Same results

I did check several fabrics with results greater and 1 and counted the patterns returned and they were correct.:
    - Grade 5 expected 5 resultes and showed 5 resutls
      Grade 3 exptected 6 results but only showed 5

**Comment by GordonPeg** [comment]
Added attachment

**Comment by hamiltonk** [comment]
Labeled and assigned as requested by PG.

**Comment by GordonPeg** [comment]
Textile testing_Test 160

**Comment by garrettbt** [comment]
More than likely those were the last 2 that were Panel and Seating. This has been fixed in the PDW but not syndicated yet.

**Comment by GordonPeg** [comment]
[Textile testing_Test 160.pdf](https://github.com/Allsteel/hni-textiles-webcomponents/files/21929/Textile.testing_Test.160.pdf)

**Comment by GordonPeg** [comment]
#220    

Reviewed the updated data and also verified the count on 3 grades.  Everything looks ok
