### ISSUE TITLE
Silvertex Vinyl Pattern Missing

### ISSUE THREAD

**Issue by hawkinscad** [Allsteel/hni-textiles-webcomponents#227]
When searching Silvertex Vinyl the pattern does not show up, but it appears that it did search for it:
![image](https://cloud.githubusercontent.com/assets/15113901/10770381/00d3708a-7cb9-11e5-93fc-9af203167dbf.png)

**Comment by garrettbt** [comment]
I have not syndicated the new order codes for this yet.

**Comment by GordonPeg** [comment]
#227
Reviewed and passed
