### ISSUE TITLE
Missing Fabric Counts - Filters

### ISSUE THREAD

**Issue by scholfieldk** [Allsteel/hni-textiles-webcomponents#228]
Review Seating Filter fabrics counts, two of which had errors:

Grade 3 - missing Silvertex

Grade 11 - 18 in production, but i don't believe the fabric "Intertwine" is either missing from QA or shouldn't be in prod. 

![capture](https://cloud.githubusercontent.com/assets/15216592/10770587/19fd7c58-7cba-11e5-8bed-55e7bcdd8386.JPG)

**Comment by garrettbt** [comment]
Intertwine was discontinued and Silvertex had the old ordercodes in PDW. A new syndication is coming that will fix these.

**Comment by GordonPeg** [comment]
Silvertex Vinyl is showing in the results and the count is correct.

I can not find Interwine in QA so I believe we need to check the MDS to see if it is an active fabric.   When I look at current AO, Intertwine comes up in search results but is missing critical data like images, order codes, etc.  It may be discontinued

**Comment by garrettbt** [comment]
Intertwine was discontinued.

**Comment by GordonPeg** [comment]
Passed
