### ISSUE TITLE
IE 11 Design Wrong

### ISSUE THREAD

**Issue by mcinnisb** [Allsteel/hni-textiles-webcomponents#232]
Based on the attached screenshot IE11 is looking crazy.

![image](https://cloud.githubusercontent.com/assets/13332532/10771704/375da330-7cc0-11e5-9263-a2fbc6507d72.png)

**Comment by felipebbtoledo** [comment]
@mcinnisb Can you confirm that IE's document mode is set to Edge? Because it looks like it is emulating an older IE version.

**Comment by mcinnisb** [comment]
@felipebbtoledo Not sure what changed, but when I went back to the page this morning it was all working correctly. Although now the magnifying glass in IE11 is upside down. I'll open a quick buck and assign it to you. So, closing this issue.

**Comment by hamiltonk** [comment]
Verified on IE11. Peg Gordon stopped by and verified for the business.
