### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by garrettbt** [Allsteel/hni-textiles-webcomponents#233]
Appoint was changed to Appoint Panel and now the images are missing.
Expresso was changed to Espresso and that image is missing.
The suppliers for Dolce, Savoy Vinyl, Stratosphere Vinyl, and Wooly were changed and now those images are missing.

**Comment by RudyValenz** [comment]
Corrected image names in Scene7. Verified that images are showing up in QA. Closed #233

**Comment by GordonPeg** [comment]
Reviewed and passed
