### ISSUE TITLE
IE 11 Search box Magnifying Glass Upsidedown

### ISSUE THREAD

**Issue by mcinnisb** [Allsteel/hni-textiles-webcomponents#236]
In IE 11 the magnifying glass is upsidedown.

![image](https://cloud.githubusercontent.com/assets/13332532/10787686/b51728ca-7d40-11e5-938d-00d4708d06bb.png)

**Comment by felipebbtoledo** [comment]
@mcinnisb This has been fixed by now. I will create a pull request for this.

**Comment by mcinnisb** [comment]
Sounds good. Once it's live and I can test I'll close.

**Comment by felipebbtoledo** [comment]
@mbr4nt I created the pull request, please merge it.

**Comment by mbr4nt** [comment]
@felipebbtoledo the search bar is on asi-paper. you couldn't possibly have fixed this in hni-textiles-webcomponents.

**Comment by felipebbtoledo** [comment]
@mbr4nt You are incorrect, both files are in the hni-textiles-webcomponents. The changed files were hni-textiles-downloads.html and hni-textiles-search-page.html Just do the merge and it will be ok.

**Comment by mbr4nt** [comment]
@felipebbtoledo no, the header is in asi-paper. Look at Brandon's screenshot, he is talking about the search bar in the header.

**Comment by felipebbtoledo** [comment]
@mbr4nt So, there were two problems in different places then. The icons in the search and download buttons were upsidedown too and now the search bar icon. Anyway, it is fixed in the new branch named searchbar, changed file is asi-paper-header.html

**Comment by mbr4nt** [comment]
@felipebbtoledo thanks, I'll test it and merge both.

**Comment by mbr4nt** [comment]
@felipebbtoledo  The icon is right side up now but it looks shift down and the breadcrumbs went quite crazy. This is in IE10.

![image](https://cloud.githubusercontent.com/assets/12057269/10792424/9fc6a882-7d5a-11e5-86ab-a82ea244e5f9.png)

**Comment by felipebbtoledo** [comment]
@mbr4nt I will need access to a machine that has the real IE10 because in IE11 and IE11 as IE10 emulation mode it does not show any issues.

**Comment by mbr4nt** [comment]
I tested it, it is fixed.

**Comment by hamiltonk** [comment]
I see this as resolved. Assigning to @mcinnisb for final test. Please change label from READYTORETEST to PASSED if you agree.
