### ISSUE TITLE
Grade Show 10 with Scroller

### ISSUE THREAD

**Issue by mcinnisb** [Allsteel/hni-textiles-webcomponents#242]
For the grade drop down can you show the first 10 with a scroll bar to show the rest.

![image](https://cloud.githubusercontent.com/assets/13332532/10831376/4f21ef00-7e53-11e5-92d0-c926cdd05faf.png)

**Comment by mbr4nt** [comment]
I went with just 5 to make sure it fits well in smaller screens.
