### ISSUE TITLE
Landing Page Hero Buttons Align to Top

### ISSUE THREAD

**Issue by mcinnisb** [Allsteel/hni-textiles-webcomponents#244]
Align the buttons for the inspiration hero slider to the scrolling image, not the HBF Textiles image. Also, if there's any chance to make the radio buttons clickable that take you to that specific image that would be ideal.

![image](https://cloud.githubusercontent.com/assets/13332532/10832955/8ce5b372-7e5c-11e5-8123-531a97fd8c82.png)

**Comment by felipebbtoledo** [comment]
@mcinnisb @mbr4nt The button's alignment has been fixed. I was not able to make the radio buttons clickable, can you do that Mateus? thanks

**Comment by mbr4nt** [comment]
I'll take care of it.

**Comment by mbr4nt** [comment]
@mcinnisb , the intention was actually to have them aligned in the middle, half way between the two panels. Fixed.
