### ISSUE TITLE
delete pedro's branch

### ISSUE THREAD

**Issue by winpHNI** [Allsteel/hni-textiles-webcomponents#25]
@mbr4nt 
please delete the branch with name "Pedro". it was a test.

**Comment by mbr4nt** [comment]
@winpHNI don't you or Pedro have access to delete it?

**Comment by winpHNI** [comment]
@mbr4nt i believe we have access. so we should be asking you for pull request then? just want to make sure i'm not doing crazy stuff wihtout you being a gatekeeper if you need. i'll delete.

**Comment by mbr4nt** [comment]
@winpHNI feel free to delete any branch you create. Just don't delete mine and don't modify master. :)

**Comment by mbr4nt** [comment]
@winpHNI @PdroCorrea 
by the way, your tests made it to the landing page branch: 
![image](https://cloud.githubusercontent.com/assets/12057269/10488194/24eef70c-725d-11e5-982b-ab713c362d65.png)

**Comment by mbr4nt** [comment]
I'm guessing this branch should be deleted as well?

**Comment by winpHNI** [comment]
@mbr4nt , @PdroCorrea ,textiles-landing-page branch is in use to test something now... don't delete :)

**Comment by mbr4nt** [comment]
Are you sure? there's nothing in it other than those 2 test commits. It basically changes the text to "back to the future". that's it.

**Comment by winpHNI** [comment]
@mbr4nt , yes i'm sure..

**Comment by mbr4nt** [comment]
I'll delete it from the server. It won't affect your local branch. I don't want anyone to branch from it and put those test commits permanently in the repository history.
