### ISSUE TITLE
The Q and R icons are incorrect

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#264]
The Q and R icons are incorrect.  The Q is four diamonds put together to make one diamond.  The R is a diamond that is outlined and not filled in (this is on the screenshot of the details page Brandon sent us in email last week).

**Comment by mbr4nt** [comment]
Tuca, I sent the icons to you on your email

**Comment by mbr4nt** [comment]
you'll have to resize them. either changing the image itself or with css.

**Comment by WilliamsHeidi** [comment]
The icons are correct but are reversed.  The quick should be the filled in diamond and the extended is the outlined image.
