### ISSUE TITLE
Remove from Configurator

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#266]
The Relate Stool with Upholstered back, Relate Task Mid Back Mesh, and Relate Stool Mid Back Mesh will all be discontinued by the end of the year.  Please remove them from the configurator.

**Comment by WilliamsHeidi** [comment]
These seats with the back type noted are being discontinued and should not show up in the Select Product section of the configurator.

**Comment by tucaz** [comment]
Deployed in QA. Can you please check to see if I removed the right ones @WilliamsHeidi? 

Thanks
