### ISSUE TITLE
Missing Configurator - Textiles Detail Page - Equation

### ISSUE THREAD

**Issue by GordonPeg** [Allsteel/hni-textiles-webcomponents#267]
Missing Configurator - Textiles Detail Page - Equation:

**Comment by tucaz** [comment]
Duplicate of #282

**Comment by WilliamsHeidi** [comment]
I was told that we had repeatables for everything but two HBF fabrics.  Can you please double-check there isn't one for this fabric?

**Comment by GordonPeg** [comment]
Reviewed and passed
