### ISSUE TITLE
Missing Configurator - Textiles Detail Page - Bevel

### ISSUE THREAD

**Issue by GordonPeg** [Allsteel/hni-textiles-webcomponents#268]
Missing Configurator - Textiles Detail Page - Bevel

**Comment by tucaz** [comment]
@WilliamsHeidi the repeatable files for this fabric have been uploaded and published. It now shows up in the configurator section when you go into the fabric details. You can test it now.

**Comment by GordonPeg** [comment]
Reviewed and passed
