### ISSUE TITLE
Search variation

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#27]
I searched the word "stripe" and got the expected results. There were several patterns with stripes displayed. However, when I searched variations like "stripes" and "striped", nothing showed. Could we look at improving searches? I could see users trying to search on variations like these.

![search_stripe](https://cloud.githubusercontent.com/assets/14330996/10485873/fdffd4aa-7251-11e5-87e3-b747143534e3.png)
![search_striped](https://cloud.githubusercontent.com/assets/14330996/10485875/fe027f70-7251-11e5-94db-1b0ca99db0ae.png)
![search_stripes](https://cloud.githubusercontent.com/assets/14330996/10485874/fe019646-7251-11e5-940b-a9e27c433b6c.png)

**Comment by mbr4nt** [comment]
moved this issue to the API project: https://github.com/HNIIT/TextilesAndFinishes/issues/11
