### ISSUE TITLE
Configurator images not loading - Textiles Detail Page - Exchange | Rhubarb

### ISSUE THREAD

**Issue by GordonPeg** [Allsteel/hni-textiles-webcomponents#275]
Configurator images not loading - Textiles Detail Page - Exchange | Rhubarb .

When I am in the detail page, I can see the product name, an outline of the space for the image, but the configurator images do not load.

**Comment by tucaz** [comment]
Fixed

**Comment by GordonPeg** [comment]
Retested and approved
