### ISSUE TITLE
Missing Configurator - Textiles Detail Page - Rock Ledge

### ISSUE THREAD

**Issue by GordonPeg** [Allsteel/hni-textiles-webcomponents#288]

**Comment by tucaz** [comment]
Repeatable tiles added and data updated in QA

**Comment by WilliamsHeidi** [comment]
Per Mateus, we will not have a repeatable image for Rock Ledge due to its complexity. Kandice has approved this as okay not to have.

**Comment by GordonPeg** [comment]
There is a configurator for Rock Ledge now.  Limited models but it is there.  Changed to passed
