### ISSUE TITLE
Missing Configurator - Textiles Detail Page - Stencil

### ISSUE THREAD

**Issue by GordonPeg** [Allsteel/hni-textiles-webcomponents#289]
Missing Configurator - Textiles Detail Page - Stencil

**Comment by tucaz** [comment]
Repeatable tiles added and data updated in QA

**Comment by WilliamsHeidi** [comment]
Per Mateus, we will not have a repeatable image for Rock Ledge due to its complexity. Kandice has approved this as okay not to have.

**Comment by GordonPeg** [comment]
Retested and approved
