### ISSUE TITLE
Incorrect Grade for some colorways of Exchange

### ISSUE THREAD

**Issue by SorensenK** [Allsteel/hni-textiles-webcomponents#292]
Exchange (seating) shows as a grade 7 and 9. It should all be grade 7.

![image](https://cloud.githubusercontent.com/assets/15238848/11936150/98c69712-a7d1-11e5-954e-50bedb72eec2.png)

**Comment by shelladyt** [comment]
@SorensenK - please update this in the Family (Pattern) spreadsheet you are working on now.

**Comment by tucaz** [comment]
@garrettbt Could you please update this data on PDW and give me a new file?
