### ISSUE TITLE
Missing product from Configurator

### ISSUE THREAD

**Issue by tjebkesk** [Allsteel/hni-textiles-webcomponents#293]
The following products need to be added to configurator-

Hedge
Access Upholstery Work 
Access Upholstery Stool

**Comment by tucaz** [comment]
@mbr4nt We don't have Hedge as new configurator and Access chairs are there. Should I close this?

**Comment by mbr4nt** [comment]
@heidi will get a quote from farm for Hedge and others.

**Comment by WilliamsHeidi** [comment]
Hedge is not a bug.  I am closing since all other seats are available.

**Comment by SorensenK** [comment]
checked 10 fabrics
