### ISSUE TITLE
Mindshare- bench, screen, bolster

### ISSUE THREAD

**Issue by tjebkesk** [Allsteel/hni-textiles-webcomponents#297]
All fabric for Mindshare is upholstered as Railroad, all tile images are pattern cut which is not correct.  Need to rotate the fabrics all 90 degrees.

**Comment by mbr4nt** [comment]
Heidi, please coordinate. 

Thank you.

**Comment by WilliamsHeidi** [comment]
This is not a bug.  This needs to be fixed in the configurator but was originally approved.  Closing as it is not a bug.
