### ISSUE TITLE
Product images download link

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#30]
The link to download an image of the product is not working. For me, it appears to be a link, but it's dead.

![download_product_images](https://cloud.githubusercontent.com/assets/14330996/10486209/8396507a-7253-11e5-8a07-e1cb7cf8cf52.png)

**Comment by mcinnisb** [comment]
Felipe if you could create the drop-down list for the Download button that contains the "Download" links that are on the current site and use the same layout you and Mateus had in the original mobile site that would be great.

**Comment by mbr4nt** [comment]
@tucaz please take a look when you have a chance.

**Comment by tucaz** [comment]
Fixed

**Comment by hamiltonk** [comment]
No longer a dead link.
