### ISSUE TITLE
Sockhop QSR data

### ISSUE THREAD

**Issue by SorensenK** [Allsteel/hni-textiles-webcomponents#303]
Sockhop is all standard and shouldn't have any symbols associated with any colors.

**Comment by tucaz** [comment]
The data attached on #304 has this with symbols. The data should be updated. Should I these colors from the data @SorensenK?

**Comment by SorensenK** [comment]
my mistake. it has been updated. the "S" was correct, but it was mislabeled with the 3 and should've been a 2.
[QSE_Standard.xlsx](https://github.com/Allsteel/hni-textiles-webcomponents/files/70980/QSE_Standard.xlsx)

**Comment by tucaz** [comment]
Data reloaded. Fixed.
