### ISSUE TITLE
Centurion QSR data

### ISSUE THREAD

**Issue by SorensenK** [Allsteel/hni-textiles-webcomponents#304]
Centurion colors should be marked with the associated "Q" symbol and are not.

**Comment by mbr4nt** [comment]
those have no "1,2,3" in the spreadsheet you gave me. Should I be using "1,2,3" or the "Q,S,E" column?

**Comment by SorensenK** [comment]
I see that the 1,2,3 was omitted and that was my error. I'm not sure which you should be using. Here is an updated version.
[QSE_Standard.xlsx](https://github.com/Allsteel/hni-textiles-webcomponents/files/70211/QSE_Standard.xlsx)

**Comment by mbr4nt** [comment]
I'll load this one, thanks.

**Comment by tucaz** [comment]
Fixed in QA
