### ISSUE TITLE
QSR - Verbiage - Hover over not working on icons 

### ISSUE THREAD

**Issue by GordonPeg** [Allsteel/hni-textiles-webcomponents#306]
QSR - Verbiage - Hover over not working on icons .  

The Q & R verbiage is not showing then I hover over the logo in the search results page.  

Tested with Chrome
Tested on Hotspot, Trisect, and Burst

**Comment by mbr4nt** [comment]
please give it a tool tip

**Comment by GordonPeg** [comment]
Retested and changed to "Passed"
