### ISSUE TITLE
Rise, Linger, Scooch Default Side and Seat Fabric

### ISSUE THREAD

**Issue by SorensenK** [Allsteel/hni-textiles-webcomponents#308]
Rise, Linger, Scooch Default Side and Seat Fabric use: Wooly Natural Heather (WOL001).

Rise, Linger, Scooch sides - Wooly Natural Heather - keep seat configurable
Rise, Linger, Scooch seat - Wooly Natural Heather - keep sides configurable

**Comment by tucaz** [comment]
Fixed in QA
