### ISSUE TITLE
Q and R Icons need to be 1/2 the size they are now

### ISSUE THREAD

**Issue by mcinnisb** [Allsteel/hni-textiles-webcomponents#309]
Shrink the icons to 1/2 the size they are now under each color way and also in the left navigation.

**Comment by tucaz** [comment]
Should I keep the same size on the details page or also reduce it there?

**Comment by mcinnisb** [comment]
Sorry reduce there as well. Make them all the same size.

Brandon McInnis
Director, e-Business

Allsteel
Mobile 563.299.2885
mcinnisb@allsteeloffice.com<http://www.allsteeloffice.com/>
allsteeloffice.com<http://www.allsteeloffice.com/>

**Comment by mcinnisb** [comment]
Another quick note on this…they should line up with just a single line of the text under a color. I should have just said that instead of ½ the size. So, make them aligned vertically to a single line vs. 2 lines high.

Brandon McInnis
Director, e-Business

Allsteel
Mobile 563.299.2885
mcinnisb@allsteeloffice.com<http://www.allsteeloffice.com/>
allsteeloffice.com<http://www.allsteeloffice.com/>

**Comment by tucaz** [comment]
Like this? 

![image](https://cloud.githubusercontent.com/assets/111954/12094880/61cd2cf4-b2f2-11e5-8bf4-a713ff6b73c6.png)

**Comment by mcinnisb** [comment]
Perfect!

Brandon McInnis
Director, e-Business

Allsteel
Mobile 563.299.2885
mcinnisb@allsteeloffice.com<http://www.allsteeloffice.com/>
allsteeloffice.com<http://www.allsteeloffice.com/>

**Comment by tucaz** [comment]
in QA
