### ISSUE TITLE
Add "Quick" facet to left navigation

### ISSUE THREAD

**Issue by mcinnisb** [Allsteel/hni-textiles-webcomponents#310]
Per a meeting with Lynda, Jason and Kandice we need to add just the "Quick" as a facet in the left nav below color. Should look like this.

![image](https://cloud.githubusercontent.com/assets/13332532/12099187/6f6c5674-b2ec-11e5-8c45-5457a0b635a2.png)

**Comment by tucaz** [comment]
In QA
