### ISSUE TITLE
Fabric Sort once a fabric is selected should be light to dark, then solid, texture, etc.

### ISSUE THREAD

**Issue by mcinnisb** [Allsteel/hni-textiles-webcomponents#311]
Per meeting with Jason, Lynda, and Kandice once a filter is selected the sort should be light to dark, then solid, texture, etc. Should follow the sort in the Excel Sheet Kandice put together. The only difference is that the initial sort order of Q,S,R is taken out.

**Comment by tucaz** [comment]
In QA
