### ISSUE TITLE
Finishes Search Page - Q & R

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#312]
Please remove the icon and descriptions for the left-hand navigation on the Finishes Search Page.

![finishes](https://cloud.githubusercontent.com/assets/13138473/12153196/44ffb618-b47e-11e5-8c43-0e9a9301b918.JPG)

**Comment by tucaz** [comment]
@williamsheidi is Brandon ok with this? I asked him this same question yesterday and he said to keep this.

**Comment by WilliamsHeidi** [comment]
Brandon is aware of this, yes.  This cannot go live on the Finishes page. It is a textiles only thing.

**Comment by tucaz** [comment]
I failed to understand that it was from the finishes pages at first. I'm sorry. I'm removing it.

**Comment by WilliamsHeidi** [comment]
Thank you, @tucaz

**Comment by tucaz** [comment]
It is in QA. Can you please validate it so I can wrap up the final package that is going to production and do the production deploy run?

Thanks!
