### ISSUE TITLE
Fabric Leadtime icon on Details page wrong size coming from the T&F Landing page

### ISSUE THREAD

**Issue by shelladyt** [Allsteel/hni-textiles-webcomponents#317]
The Fabric Leading icon the Textiles Detail page is elongated when coming from the Textiles & Finishes Landing Page inspiration tiles swatch.

Steps to reproduce:
Textiles & Finishes Landing Page -> Warm Neutrals hero image -> select any of the bottom three swatches (Narrative Pebble, Appoint Seating - Bronze and Wooly - Marine) -> Goes to the Details page -> Fabric Leadtime icon in the Attribute list does not match the size of the icon on the Search page.

Testing on IE11 and Chrome.

**Comment by WilliamsHeidi** [comment]
@shelladyt this is ready to retest

**Comment by WilliamsHeidi** [comment]
@tucaz when you go to the T & F landing page, the insprational images that scroll across the top with the clickable tiles down the right side.  if you go to the image labeled 'Warm Neutrals' and click any of the last three fabrics on the side, the image for Q & R in the attribute list is stretched.

**Comment by tucaz** [comment]
I fixed it @WilliamsHeidi. Since you have seen the broken version now you are seeing cache. Please refresh your browser a couple of times to see the fixed version.
