### ISSUE TITLE
Landing Page - Inspiration Image

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#39]
Expected result: This is a rotating, image that is changed out occasionally. The image tiles should be clickable and lead to their respective pattern/color detail pages.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Examine the page to make sure the inspiration image tile is displayed
4. Click each colorway to make sure it leads to the fabric's details page

**Comment by GordonPeg** [comment]
Passed
Chrome
