### ISSUE TITLE
Landing Page  - HBF Textiles Tile

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#42]
This tile will bring users to the textiles search page, but the offerings will be pre-filtered to fabrics that are sold by HBF.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the HBF Textiles tile

**Comment by GordonPeg** [comment]
Passed
Chrome
