### ISSUE TITLE
Search Page - Header

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#44]
Expected Result: Check the page header. The page header should be leveraged from all other Allsteel sites. The functionality of the menus, site search and breadcrumbs should match that of other Allsteel sites.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Inspect the page header and compare against www.allsteeloffice.com - they should match
5. Test the links on the header to ensure they are live and direct users to the correct pages
6. Test the search in the header to ensure it is live and produces search results

**Comment by hamiltonk** [comment]
Kristi Scholfield tested in Chrome and here were the results:

![header](https://cloud.githubusercontent.com/assets/14330996/10647407/c3e441f0-77fd-11e5-9217-c2da00112af8.png)

**Comment by mbr4nt** [comment]
@hamiltonk , as discussed, test failures should be open as a new issue, not a comment on the test scripts. Team and I won't be monitoring any issues labeled as "test-script". please move this to a new issue. Thank you.

**Comment by mcinnisb** [comment]
Just reviewed the two side by side and looks like the issues were corrected.
