### ISSUE TITLE
Search Page - Fabric Search

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#45]
Expected Result: In the LeftNav, the search field is setup to be able to search fabrics. Try using several different terms in this field. Examples include colors/color families, fabric pattern names, color names, grades, etc. When a term is searched, the search page should display with results.

WARNING: This test script will take a long period of time to execute.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Search the term 'green'
5. Ensure that green fabrics show as a result
6. Search the term 'stripe'
7. Ensure that striped fabrics show as a result
8. Search the term 'copper'
9. Ensure that fabrics named Copper (or with copper in the name) show as a result
10. Search the term 'appoint'
11. Ensure that the Appoint families display
12. Repeat with other searches based on colors, grades, fabric content and other attributes

Attributes list for searching:
o Pattern Name
o Color Name
o Order Code
o Application
o Content
o Abrasion
o Width
o Repeat
o Weight
o Finish
o Backing
o Flame Resistance
o Maintenance
o Manufacturer (for partnership)
o Grade

**Comment by hamiltonk** [comment]
Sami Miller tested in Chrome. Here is her feedback:

Green Search pulls Green but some other colors as well, such as pattern I-Beam, color Molten (listed as Red on AO.com). I tried to replicate but this time it didn’t pull up anything but green. It is missing some color blocks:

![image](https://cloud.githubusercontent.com/assets/14330996/10649989/a045c39a-780c-11e5-999c-7f1ae889aa33.png)

Searched Red and missing a color.  Also, it pulled some colors that are listed on AO in other color families, such as Article, Butterscotch which is listed as beige.

![image](https://cloud.githubusercontent.com/assets/14330996/10650004/b59d2544-780c-11e5-804a-ad2083ba1187.png)

![image](https://cloud.githubusercontent.com/assets/14330996/10650008/beb223f0-780c-11e5-9b92-7b3b3a8c580e.png)

Searching Yellow also pulls beige colors and even a Blue Green. 

![image](https://cloud.githubusercontent.com/assets/14330996/10650013/ca76ce70-780c-11e5-8882-ff7e7fc9e0e0.png)

![image](https://cloud.githubusercontent.com/assets/14330996/10650017/d2f17212-780c-11e5-93c0-b0cfc7ef1076.png)

I tried searching Pattern, Floral, and Floral/Leaf but no results (I confirmed on AO that we do have fabrics listed as floral/leaf pattern).

Geometric and Blue were good.

**Comment by mcinnisb** [comment]
Garrett, can you re-assign the color ways above to the right color categories. I know there will be more as we clean them up, but want to tackle the ones we currently know of.

**Comment by garrettbt** [comment]
All color families were updated using the file provided by Kandice. The examples above are in the correct families according to that file. If changes are needed, a new file is required with new values.
