### ISSUE TITLE
Search Page - COM Search Button

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#46]
Expected Result: Clicking this button will bring users to the COM search experience. The COM experience does not need to be tested from this point; only getting to COM.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Click the COM button

**Comment by braunsa** [comment]
Tested in Chrome. Passed
