### ISSUE TITLE
Search Page  - Download Button

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#47]
Expected Result: The download button provides a way for users to download PDFs that are supplied by Allsteel. This is predefined content and does not change with the fabric search results. 

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Click the Download button.
5. Select a file to download.
6. Open the PDF file.
7. Repeat steps 4-6 with two additional files.

**Comment by hamiltonk** [comment]
Kristi Scholfield tested this in Chrome and the following files do not download. There is a "page cannot be displayed" error.

Allsteel Care Guide - doesn't work
Beyond Textured Paint Card - doesn't work
HBF Textiles Product Matrix - doesn’t work
HBF Textiles Sell Sheet - doesn’t work
System and Seating Fabric Matrix - doesn't work

**Comment by mbr4nt** [comment]
This is due to QA not having all documents. When you get a 404, replace the qa url with a prod one and you should get the files.
