### ISSUE TITLE
Search Page - Color Family Filter

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#48]
Expected Results: These links will allow users to filter fabric offerings by color family. Clicking an option will narrow results to that color family. Clicking multiple options will allow users to see results from all of the selected color families. All color families will need to be tested.

The following color families will be available: White, Cream, Taupe; Beige, Gold, Yellow; Brown; Red, Orange; Blue, Turquoise; Green; Burgundy, Purple; Grey; Black

Steps:

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select the White, Cream, Taupe color family.
5. Compare at least 2 colorways each from at least 10 pattern groups to this spreadsheet: http://hni.hnicorp.com/sites/ITProjectManagement/15-0062/Documents/GoLiveData/Copy of Copy of PDWExportByColorWay- KKT.xlsx
6. Clear the color filter
7. Repeat steps 4-6 for these color families, clearing the filter after each validation: Beige, Gold, Yellow; Brown; Red, Orange; Blue, Turquoise; Green; Burgundy, Purple; Grey; Black

**Comment by GordonPeg** [comment]
Pass  -  Chrome
