### ISSUE TITLE
Search Page - Fabric Grade Filter

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#49]
Expected Result: This filter will allow users to narrow their search by a particular grade of fabric. Clicking this option will narrow results to a specific grade. Multiple filters can be selected.  All grades must be tested to pass.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. In the LeftNav, select the Panel A filter
5. Compare results against live allsteeloffice.com website
6. Clear the filter
7. In the LeftNav, select the Panel F filter
8. Compare results against live allsteeloffice.com website
9. Clear the filter
10. In the LeftNav, select the Seating 10 filter
11. Compare results against live allsteeloffice.com website
12. Clear the filter
13. In the LeftNav, select the Seating 7 filter
14. Compare results against live allsteeloffice.com website

**Comment by tjebkesk** [comment]
tested in IE11 and passed.  Other bugs logged
