### ISSUE TITLE
Search Page - Pattern Groupings

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#53]
Expected Results: Patterns should be displayed with colorways sorted lightest-to-darkest.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Inspect the following 20 patterns to make sure colors are sorted lightest-to-darkest:

- Appoint
- Mica
- Sarto
- Seed
- Luster
- In Season
- Freeway
- Burnished Cloth
- Smooth
- Forest Light
- Bumpy
- Glint
- Play
- Belgian Meadow
- Alloy
- Bravo
- Metric
- Reply
- Sketch
- Scribe

NOTE: Other patterns may be inspected as well.

**Comment by hawkinscad** [comment]
Tested on Chrome and this passes

**Comment by hamiltonk** [comment]
Carlee Hawkins tested this in Chrome, as it is a pass.
