### ISSUE TITLE
Search Page - Filtered Pattern List

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#54]
Expected Result: When filtered, the applicable results should be displayed from lightest-to-darkest. Any patterns which do not meet the search criteria should not be displayed.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Apply any filter (Ex: Color Family = Green)
5. Inspect the colors available to ensure they are lightest-to-darkest
6. Clear the filter applied
7. Repeat steps 4-6 several times; each time the results should be the same

**Comment by GordonPeg** [comment]
Pass
Chrome
