### ISSUE TITLE
Search Page - Color Names

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#55]
Expected Result: The name of the color should be displayed below the colorway. It should match the color name in the details page.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Check the names of colors under the colorways; compare against live allsteeloffice.com website

![image](https://cloud.githubusercontent.com/assets/14330996/10618466/b83dc5e2-7735-11e5-87d9-4d7bcbeda823.png)

**Comment by GordonPeg** [comment]
Pass

Chrome
