### ISSUE TITLE
Search Page - Footer

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#62]
Expected Result: The footer should be leveraged and the same as all other Allsteel sites. The functionality of links, social media buttons, etc. should match other Allsteel content.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Apply filters (to reduce the number of patterns displayed for scrolling purposes)
5. Inspect the page footer and compare against www.allsteeloffice.com - they should match
6. Test the links on the footer to ensure they are live and direct users to the correct pages

**Comment by hamiltonk** [comment]
Kristi Scholfield tested on Chrome and there are these issues:

1. The alignment of the columns does not match.
2. The Allsteel logo and About us links do not function; there is just an error.

![footer-alignment](https://cloud.githubusercontent.com/assets/14330996/10646656/e0862b4c-77f9-11e5-894f-ec51ef4731ad.JPG)
![footer-links](https://cloud.githubusercontent.com/assets/14330996/10646657/e08acb20-77f9-11e5-8bec-44e679d6976f.JPG)

**Comment by mbr4nt** [comment]
Fixed, except for column alignment, which will be different to support responsive design to be mobile friendly. I already met with Kristi and explained.
