### ISSUE TITLE
Search Page - Pattern Order

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#63]
Expected Result: Fabric pattern names are to be displayed in alphabetical order on the search page. 

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Scroll through the page and look at the pattern names
5. Apply any filter (color family, pattern, etc.)
6. Scroll through again and look at the pattern names

**Comment by hamiltonk** [comment]
Sami Miller tested this is Chrome. The patterns are not in alphabetical order on the site. For example, Tango came before Attire. There were several others out of order as well.

**Comment by mcinnisb** [comment]
@mbr4nt What is the default sort criteria for textiles? I also need to confirm with Kandice what she wants the default sort order to be, but want to understand how it's sorting currently.

**Comment by mbr4nt** [comment]
@mcinnisb, short answer: Pattern Type, then Supplier, then alpha.

long answer: 

First come the "Solid" fabrics, then "Solid/Texture", "Texture", "Geometric", "Organic", "Stripe" and "Plaid".

Inside each of those groups, they are then sorted by Supplier, like this: "Allsteel", "HBF Textiles", "Maharam", "Momentum" and last "Ultrafabrics".

Those rules came from a spreasheet I got from Heidi, which I believe she was given by Kandice.

Then, inside each Pattern Type / Supplier combination, results are sorted by name.

So, the first fabrics to show up should be "Solid" pattern type fabricc from "Allsteel" supplier, sorted by name.

**Comment by mcinnisb** [comment]
Closing this issue. Resolved based on review with Kandice. Facet sort is correct as is. The initial sort when you land on the textiles search page will be brand, alphabetical.
