### ISSUE TITLE
Details Page - Header

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#64]
Expected result: The page header should be leveraged from all other Allsteel sites. The functionality of the menus, site search and breadcrumbs should match that of other Allsteel sites.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern; click the colorway
5. Check all facets of the page header

**Comment by braunsa** [comment]
Tested in Chrome and passes
