### ISSUE TITLE
Details Page - Back-to-Search Link

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#66]
Expected result: This link will return users to the search page and the last search results.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern; click the colorway
5. Click the BACK TO SEARCH link above the hero image

![image](https://cloud.githubusercontent.com/assets/14330996/10693647/34d5c386-795f-11e5-862b-44f915981dbf.png)

**Comment by braunsa** [comment]
When clicking back to search it takes you to the top of the page rather than the area of the page you were in previously.

#66
