### ISSUE TITLE
Details Page - Hero Image

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#67]
Expected result: There will be a large image of the selected pattern/color combination displayed next to the attributes.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern; click the colorway
5. Examine the page for a hero fabric image

**Comment by braunsa** [comment]
Images are smaller then they should be,
![image](https://cloud.githubusercontent.com/assets/15125108/10695558/dd94ef7e-7969-11e5-9864-eb1e9d21dd7e.png)

#67
