### ISSUE TITLE
Details Page - Pattern Name and Color

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#71]
Expected result: The pattern and color names will be displayed as PATTERN – COLOR before the fabric attributes.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern; click the colorway
5. Check the attribute list for the pattern and color names

**Comment by GordonPeg** [comment]
Passed

Chrome
