### ISSUE TITLE
Details Page - Fabric Grade

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#72]
Expected result: The fabric’s grade (panel and/or seating) will be displayed as a part of the attributes.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern; click the colorway
5. Check the attribute list for the fabric grade

**Comment by WilliamsHeidi** [comment]
above issue is passed and closed
