### ISSUE TITLE
Details Page - Order Code

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#73]
Expected result: The order code for the fabric is displayed. It will be a combination of the pattern and color order codes. This will change as the hero image is changed.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern; click the colorway
5. Check the attribute list for the order code

**Comment by GordonPeg** [comment]
Passed
Chrome
