### ISSUE TITLE
Details Page - Social Media Sharing

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#76]
Expected Results:
	Facebook – Allows users to post to Facebook. When sharing to social media, the image should be the currently-active hero swatch. The test will be as follows: Fabric Family/Color Name Short URL @Tag (Example: Peas in a Pod/Thunder & Lightening alls.tl\shbfppd10 @Allsteel)
	Twitter – Allows users to post to Twitter. When sharing to social media, the image should be the currently-active hero swatch. The test will be as follows: Fabric Family/Color Name Short URL @Tag (Example: Peas in a Pod/Thunder & Lightening alls.tl\shbfppd10 @Allsteel)
	Instagram – Allows users to post to Instagram. When sharing to social media, the image should be the currently-active hero swatch. The test will be as follows: Fabric Family/Color Name Short URL @Tag (Example: Peas in a Pod/Thunder & Lightening alls.tl\shbfppd10 @Allsteel)
	Pinterest – Allows users to post to Pinterest. When sharing to social media, the image should be the currently-active hero swatch. The test will be as follows: Fabric Family/Color Name Short URL @Tag (Example: Peas in a Pod/Thunder & Lightening alls.tl\shbfppd10 @Allsteel)

NOTE: Links should be to the left of email/print.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern; click the colorway
5. Click on the Facebook sharing link
6. Use the test Facebook account to share the pattern
7. Click on the Twitter sharing link
8. Use the test Twitter account to share the pattern
9. Click on the Instagram sharing link
10. Use the test Instagram account to share the pattern
11. Click on the Pinterest sharing link
12. Use the test Pinterest account to share the pattern

**Comment by WilliamsHeidi** [comment]
sharing on social media is working
