### ISSUE TITLE
Details Page - Attribute List Data

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#77]
Expected result: Data matches data in pricer/MDS/fabric cards.

WARNING: This Will need to be compared by someone who knows the fabric, or against fabric cards.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern; click the colorway
5. Check to make sure fabric attributes are displayed correctly. Check all of the colors on at least 30 different patterns all of which have a minimum of four color offerings.

**Comment by SorensenK** [comment]
Checked 30 random patterns. The color information and codes match. There are a few punctuation and consistency errors, but fixing those will be with blanket statements (TBD) in a larger data overhaul at a later date.
