### ISSUE TITLE
Details Page - Attribute List Order

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#78]
Expected result: The order should be as follows:
o	Pattern Name
o	Color Name
o	Order Code
o	Application
o	Content
o	Abrasion
o	Width
o	Repeat
o	Weight
o	Finish
o	Backing
o	Flame Resistance
o	Maintenance
o	Product Restrictions/Exceptions (Notes)
o	Manufacturer (for partnership)
o	Grade
o	ACT Icons

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern; click the colorway
5. Check the attribute order

**Comment by WilliamsHeidi** [comment]
@hamiltonk Here is what I have for the ordering of attributes
![image](https://cloud.githubusercontent.com/assets/13138473/10700889/63529d2a-7986-11e5-91dc-93af7924379d.png)

With the exception of ACT registered symbols, which won't show a go-live
