### ISSUE TITLE
Details Page - Colorways

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#79]
Expected result: The colorways will show all of the available colors for the fabric pattern. Clicking a colorway will change the hero image, take the color out of the colorway list and apply the color to the product displayed in the configurator. 

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern; click the colorway
5. Click a colorway below the hero image
6. Compare the color that is displayed in the hero image and configurator against the color selected
7. Repeat steps 5 and 6 for all available colors

**Comment by kensrudl** [comment]
tested in Chrome, passed. Tried on 5 different color patterns.

**Comment by hamiltonk** [comment]
Response to bug 183:

To make a configurator show, the fabric needs to:
1 - be available on the product
2 - be in scene7 as a repeatable tile. Not all fabrics are there at this point nor will be available for launch.

For the ones that meet both criteria, the configurator shows up like it should.

I'm closing this issue.
