### ISSUE TITLE
Details Page - Configurator Display

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#80]
Expected result: Product is displayed correctly and with the correct pattern and color applied.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern; click the colorway
5. Compare the color of the fabric on the product in the configurator against the hero image above
6. Click another colorway to change the color in the hero image
7. Compare the product again
8. Repeat steps 6 and 7 for all of the colorways in the pattern
9. Repeat steps 4-8 for at least five additional patterns

**Comment by GordonPeg** [comment]
Reviewed 3 textiles and 4-5 colors each on multiple products.  Passed
