### ISSUE TITLE
Details Page - Configurator Product Change

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#81]
Expected result: User can change the product in the configurator. (The product list will be restricted to only those products that the fabric can be applied to.)

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern; click the colorway
5. Scroll down to the product configurator section
6. Click the CHANGE PRODUCT drop-down
7. Select a new product from the list
8. The product in the configurator will change, with the hero image color applied
9. Repeat steps 5-8, using at least five additional fabric patterns

**Comment by GordonPeg** [comment]
Reviewed 5 textiles and 3-4 products for each one.  Passed
