### ISSUE TITLE
Details Page - Configurator Image Download

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#82]
Expected result: Link allows user to download an image of the product with the hero image color applied.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern; click the colorway
5. Scroll down to the product configurator section
6. Click the DOWNLOAD link
7. A new tab/window will open with a downloadable version of the product; right-click to save
8. Open the downloaded image and compare the color against the hero image
9. Change to a different color in the same pattern
10. Repeat steps 5-9 for a total of five image downloads

**Comment by kensrudl** [comment]
Tested in Chrome Passed
