### ISSUE TITLE
Details Page - Configurator Rotation

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#83]
Expected result: Clicking on the rotation images will change the configurator’s rotation as well.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern; click the colorway
5. Scroll down to the product configurator section (below the colorways)
6. One at a time, click on the available product rotations and compare against the large configurator image - they should match

![image](https://cloud.githubusercontent.com/assets/14330996/10639749/6c78463a-77d7-11e5-9e80-2bba3e4d8b42.png)

**Comment by GordonPeg** [comment]
Reviewed 3 textiles and passed.
