### ISSUE TITLE
Details Page - 'Available On' Product List

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#84]
Expected Result: This is a list of products which the fabric can be applied to. Clicking on the product tiles will take users to the page for that particular product.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Textiles (Fabrics) tile
4. Select any colorway from any pattern; click the colorway
5. On the details page, scroll down to the AVAILABLE ON section
6. Review the products that the fabric is available on; compare against live allsteeloffice.com website
7. Scroll to the top of the page
8. Click the BACK TO SEARCH link
9. Repeat steps 4-8 on at least five additional patterns

**Comment by WilliamsHeidi** [comment]
above issue is closed and passed.
