### ISSUE TITLE
Finishes Page - Loading

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#85]
Expected result: The legacy finishes page should load at this time. The experience is only skinned with a new look.

1. Navigate to qa.allsteeloffice.com
2. Go to Design Resources > Textiles + Finishes
3. Click on the Search Finishes tile
4. Verify finishes page loads and colorways are clickable

**Comment by WilliamsHeidi** [comment]
above issues were closed and passed.  closing test script
