### ISSUE TITLE
Textiles Search Page - Pricing Grade

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#89]
Pricing Grade needs to be a drop-down list.

**Comment by mbr4nt** [comment]
Do you mean the facet? If so, customizing one facet is going to be complicated. I'd say post-launch, maybe.

**Comment by mcinnisb** [comment]
Price Grade needs to be a drop-down for launch.There are way to many options to keep it in the list form it is today.

**Comment by mbr4nt** [comment]
@mcinnisb did we give up on organizing (and simplifying) the list like we did with color family? I think that this issue is bigger than how to display it. If the list is extensive like it is now it doesn't really help people filtering.

**Comment by mbr4nt** [comment]
How about if we make the facets collapsed by default, like it is today in AO?

**Comment by mcinnisb** [comment]
@mbr4nt Are we unable to make it a drop-down list?

**Comment by mcinnisb** [comment]
If we can make it a drop down that would be ideal. An accordion menu is option B if it’s not possible to make a drop down.

Brandon McInnis
Director, e-Business

Allsteel
Mobile 563.299.2885
mcinnisb@allsteeloffice.com<http://www.allsteeloffice.com/>
allsteeloffice.com<http://www.allsteeloffice.com/>

**Comment by mbr4nt** [comment]
@mcinnisb ok. So let's create a criteria to make a facet render as a dropdown. I'm understanding it's for long lists. What should be our threshold? more than 15 items, maybe?

**Comment by mcinnisb** [comment]
Yeah, I think that makes sense, although would be good to still be able to override based on direction.

Brandon McInnis
Director, e-Business

Allsteel
Mobile 563.299.2885
mcinnisb@allsteeloffice.com<http://www.allsteeloffice.com/>
allsteeloffice.com<http://www.allsteeloffice.com/>
