### ISSUE TITLE
Textiles Search Page - Application

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#90]
The Application filter on the left-hand navigation needs to pull from the Display Name field in PDW, which contains the only two options that should be available - Seating, Panel.

**Comment by mbr4nt** [comment]
I'm reading from the application field, which seems more reliable to me. I'd advice to keep as is.

**Comment by WilliamsHeidi** [comment]
If you would like to continue to pull from the application field, that is fine.  We just need clean up the data.  The only two options that should show in the Application attribute, according to the business requirements, is Seating and Panel.

**Comment by mcinnisb** [comment]
This will be data clean-up, which we'll assign to Garrett as soon as he shows up in GitHub.

**Comment by garrettbt** [comment]
What is the expected result when a fabric can be used for both Panels and Seating. Currently in the PDW, we separate by a comma. For example Seating, Panel.

**Comment by mbr4nt** [comment]
@garrettbt keep the comma.
