### ISSUE TITLE
Textiles Search Page - Filtering

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#91]
[AppliedFilters_X.docx](https://github.com/Allsteel/hni-textiles-webcomponents/files/14365/AppliedFilters_X.docx)
When there is an Applied Filter the 'X' to unselect the filter is too small.

For example: If I click on the Color Family: Beige, Gold, Yellow.  There is an Applied Filters: field that appears at the top of the left-hand navigation.  The 'x' that appears here is not noticeable.

Please see attached screenshots.

**Comment by mcinnisb** [comment]
This is the same issue that I logged at 108. I included screenshots in the 108, so going to close this bug and keep it open with 108.
