### ISSUE TITLE
Textiles Search Page - Color Family Blue Green

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#92]
Blue Green is not one of the new color families.  Ultraleather: Mystic needs to be changed to Green in the DB.

**Comment by mcinnisb** [comment]
Brandon Garrett owns the data piece. My understanding is he get's the data from the textiles team (i.e. Kandice). I don't see him in Github. I'll shoot him a note and CC you ,but we should get him in Github, so any data related issues I can assign to him.

**Comment by mbr4nt** [comment]
@garrettbt this still comes in the syndication
