### ISSUE TITLE
Textiles Search Page - Color Family Burgundy & Purple

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#95]
When selecting Burgundy & Purple in the color family filter, the Applied Filters at the top of the left-hand column shows "Color Family: Burgundy". Should it show "Color Family: Burgundy & Purple"?

**Comment by mbr4nt** [comment]
all those you opened about filters with the "&" in the name are all caused by the same thing, i'll fix them all.

**Comment by WilliamsHeidi** [comment]
I thought they were.  The fact that it isn't returning a result, is that also due to this issue?  If so, should I be connecting them all together somehow?
