### ISSUE TITLE
Textiles Search Page - Color Family Red & Orange - no search results

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#98]
When selecting the Red & Orange from the color family filter, there are no search results.

**Comment by mcinnisb** [comment]
Just selected Red & Orange and it returned "Red & Orange" results. Can you verify again that there aren't any results.

**Comment by WilliamsHeidi** [comment]
@mbr4nt are these ready to re-test?
