### ISSUE TITLE
Textiles Search Page - Pattern Type

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#99]
Organic is no longer a Pattern Type.  Can I get a list of the fabrics that show as Organic so they can be reclassified?  The only Pattern Types are : Solid, Solid/Texture, Geometric, Stripe, and Plaid.

**Comment by mbr4nt** [comment]
just click the facet, it should give you the list

**Comment by mcinnisb** [comment]
If Organic is no longer a pattern type that needs to be updated in the data. Brandon Garret should be able to assist making the updates, but will need to know what Pattern Types they should be changed to, which I'm assuming will come from Kandice, unless we already have the patterns to categories somewhere, in which case I believe we just need to get that updated list to Brandon Garrett who will then get it to Mateus.

**Comment by WilliamsHeidi** [comment]
I will have to have Kandice recategorize.  She has done this once but, as we see, she must have missed some.  Can we get a list of just the ones coming up as Organic?

**Comment by mcinnisb** [comment]
Click on Organic and it will pull back the results that are currently listed as Organic.

**Comment by WilliamsHeidi** [comment]
I have an email out to Kandice to confirm if Organic will be used as a Pattern Type or if these need to be recategorized.

**Comment by WilliamsHeidi** [comment]
Kandice has confirmed that Organic is a Pattern Type
